version: '2'
services:
  datastore:
    image: busybox
    volumes:
      - postgres-data:/var/lib/postgres
      - redis-data:/data
      - bundle_install:/rails_with_postgresql/vendor/bundle
      - bundle:/rails_with_postgresql/.bundle
      - node_modules:/rails_with_postgresql/node_modules
  postgres:
    image: postgres
    networks:
      - default
    ports:
      - '5432:5432'
    volumes_from:
      - datastore
  redis:
    image: redis:alpine
    networks:
      - default
    ports:
      - '6379:6379'
    volumes_from:
      - datastore
  web:
    build:
      context: .
      dockerfile: Dockerfile-dev
    depends_on:
      - postgres
      - redis
    networks:
      - default
    volumes:
      - .:/rails_with_postgresql
    ports:
      - "3000:3000"
    volumes_from:
      - datastore
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
volumes:
  postgres-data:
    driver: local
  redis-data:
    driver: local
  bundle_install:
    driver: local
  bundle:
    driver: local
  node_modules:
    driver: local